site:
  title: RapidClipse Reference Manual
  url: https://info.rapidclipse.com/
  start_page: rc11::index.adoc
content:
  sources:
  - url: https://github.com/RapidClipse/rapidclipse
    start_path: docs
    branches: [11.0]
ui: 
  bundle:
    url: ./theme/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'
