site:
  title: RapidClipse Reference Manual
  url: https://info.rapidclipse.com/
  start_page: index.adoc
content:
  sources:
  - url: https://github.com/EliasKeilhammer-XDEV/AntoraTest
    start_path: docs/ger
    branches: [main]
  - url: https://github.com/EliasKeilhammer-XDEV/AntoraTest
    start_path: docs/en
    branches: [main]
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'
