site:
  title: RapidClipse Reference Manual
  url: https://info.rapidclipse.com/
  start_page: docs/index.adoc
content:
  sources:
  - url: https://github.com/EliasKeilhammer-XDEV/AntoraTest
    start_path: docs
    branches: [main]
ui: 
  bundle:
    url: ./theme/build/ui-bundle.zip
    snapshot: true
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'
