site:
  title: RapidClipse Reference Manual
  url: https://info.rapidclipse.com/
  robots: allow
content:
  sources:
  - url: https://${{ secrets.TOKEN }}:@github.com/RapidClipse/rapidclipse.git
    branches: release/11.0
    start_path: docs
asciidoc:
  attributes:
    page-pagination: ''
    source-language: asciidoc@
ui: 
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'
