site:
  title: RapidClipse Reference Manual
  url: https://info.rapidclipse.com/
  start_page: rc::index.adoc
content:
  sources:
  - url: https://github.com/RapidClipse/rapidclipse
    start_path: docs
    branches:
      - "11.0"
      - "12.0"
ui: 
  bundle:
    url: https://github.com/EliasKeilhammer-XDEV/rapidclipse-documentation-theme/releases/download/v1.15.0/rapidclipse-documentation-theme-v1.15.0.zip
    snapshot: true
output:
  dir: ./site
antora:
  extensions:
  - require: '@antora/lunr-extension'
