= Overview

== About RapidClipse

RapidClipse is a free Eclipse distribution for rapid cross-platform development with Java. RapidClipse is Eclipse - but preconfigured, extended with additional tools and optimized in many places to simplify professional application development with Java and Eclipse.

=== Notice:

*Visual and rapid* - The terms *visual* and *rapid* in the explanation of RapidClipse are meant to express that application development with RapidClipse is easier and more comfortable than with the standard Eclipse installation. However, to infer from this that the possibilities with RapidClipse or the size of the solutions developed with it must be severely limited is completely wrong. RapidClipse is a preconfigured Eclipse installation enhanced with additional plug-ins and frameworks and thus has all the features and capabilities of the standard Eclipse installation. The tools and APIs included in RapidClipse are simplifications that you can use, but do not necessarily have to use. Features that are not suitable for your use case can always be replaced by other Java APIs or your own implementations. Switching from RapidClipse to Eclipse is therefore not a switch, but only a renunciation of tools that RapidClipse provides.
* *Unexpected complexity* - RapidClipse greatly simplifies getting started with Eclipse and application development with Java - but don't forget - RapidClipse is Eclipse. Due to the large number of Eclipse plugins, tools and APIs used in RapidClipse as well as the powerful Eclipse IDE itself, there are numerous setting and configuration options. This can also lead to problems in practice. Most of the time, these problems are not caused by RapidClipse bugs, but by incorrect settings, which can easily be fixed with some Eclipse experience. If you encounter such problems, please seek help in our free community forum or contact our RapidClipse support team. In our training courses you will get to know Eclipse very quickly, so that you can recognize the most common configuration problems right away and solve them yourself.
* *Moving from RapidClipse to Eclipse* - You don't have to think about whether a later move to Eclipse is possible. RapidClipse is Eclipse. Once you stop using RapidClipse's tools, there is no difference. Code generated by RapidClipse behaves exactly like code written by hand, so you can continue to use it without RapidClipse tooling. Only the dependencies on the RapidClipse Open Source Framework remain, as with any other Java framework.

=== All important plugins and frameworks already preinstalled

In RapidClipse, all important Eclipse plug-ins needed for professional application development with Java are already pre-installed, pre-configured, and coordinated. The usual setup and configuration effort for Eclipse is completely eliminated with RapidClipse.

=== Additional Tools & APIs

The Eclipse plugins and frameworks used in RapidClipse are not only integrated, but optimized if necessary and extended with new tools and APIs developed specifically for RapidClipse to make their use easier and more comfortable for you. An example of this is the greatly improved Hibernate import of the JBoss Hibernate tools in RapidClipse.

=== Maven

RapidClipse projects are based on Maven. At project start, Maven automatically downloads all Java libraries (JARs) required for the project start as well as subsequently included Java libraries (JARs) from the central Maven repository (Maven-Central), automatically adds all dependencies to the *pom.xml* configuration file provided for this purpose, so that you do not have to deal with this anymore.

=== HTML 5 surfaces

RapidClipse applications are always Java web applications that feature a modern HTML5 interface.

=== RapidClipse Framework

With the RapidClipse Framework, RapidClipse also provides a databinding between Vaadin and Hibernate as well as a complete architecture and many important application infrastructure services that almost every modern business application needs. The application developer is freed from complicated low-level programming and can focus on business logic and user interface design.

=== Cross-Platform Development

With the RapidClipse deployment tools, any project can be deployed as a web application.

=== Microstream.one - Java In-Memory Database

RapidClipse enables easy creation and setup of Microstream.one, a Java in-memory database

=== Most important RapidClipse components

* Eclipse
* Java SE
* Java Persistence API (JPA)
* JBoss Hibernate Tools
* Git
* Maven
* Vaadin
* RapidClipse IDE Tools
* RapidClipse Framework
* Microstream.one integration

=== RapidClipse IDE Tools

* RapidClipse Vaadin GUI Builder
* RapidClipse Hibernate Tools
** RapidClipse JPA-SQL Code Editor
** Entity Editor
** RapidClipse Hibernate Import Function
** Sample Database
* RapidClipse Cross-Platform Deployment Tools

== Target group

RapidClipse is aimed at:

* Professional application developers who want to use Eclipse to develop sophisticated business applications based on Java as quickly and easily as possible.
* Java developers who have little or no experience with JPA and Hibernate.
* 4GL (4th Generation Language) developers who want to move from 4GL development environments to Java as quickly and easily as possible to port important legacy applications to Java.
* Java beginners who want to achieve productive results as quickly as possible.
* GUI designers who want to create graphical interfaces by drag and drop or declaratively and do not want to get in touch with Java code.

== System requirements

To run RapidClipse and applications developed with it, your system should meet the following requirements:

=== Development environment:

==== Hardware:

* RAM: min. 8 GB recommended
* Hard disk space: 1 GB - 5 GB SSD recommended
* Monitor resolution: 1920 x 1080 recommended

==== Software:

* Windows 7, 8, 10, 11
* Java Development Kit (JDK) Version 11
* Proxy - Set up under *Window* > *Preferences* > *General* > *Network Connections*.

==== Internet:

* First start of RapidClipse - Internet connection mandatory. If the Internet connection is slow, loading the required dependencies may take a long time.
* Existing RapidClipse project - offline mode possible, but needs to be enabled, under *Window* > *Preferences* > *Maven* > *Offline*.

==== Supported databases:

* Microstream.one
* Generic JDBC
* DB2 for z/OS
* DB2
* Derby
* Firebird
* H2
* HSQLDB
* Informix
* Ingres
* MaxDB
* MS SQL Server
* MySQL
* Oracle
* PostgreSQL
* SQLite
* Sybase ASA/ESA
* More with Hibernate dialect via JDBC

=== Target environment:

* Java Runtime Environment Version 11
* Web server
* Application server (any, must support Java Servlet 3.0/3.1/4.0. Servlet container sufficient, e.g. Tomcat).
* Browser: Chrome, Firefox, Safari, Edge, Opera