name: Antora Documentation Build

on:
  push:
    branches:
      - master  # Main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Node.js version

      - name: Install Antora
        run: npm install -g @antora/cli@2  # Antora version you want

      - name: Build Antora Documentation
        run: antora antora-playbook.yml  # Playbook file

      - name: Install Lunr Search Extension
        run: npm install @antora/lunr

      - name: Generate Lunr Search Index
        run: antora --generate --search-index

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site  # Output directory
          publish_branch: site   # Branch for deployment
